name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - run: |
          set -x
          which gcc
          gcc -v
          gcc -dM -E - < /dev/null | grep __MINGW || true
        shell: bash
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - uses: ruby/setup-ruby@80740b3b13bf9857e28854481ca95a84e78a2bdf # v1.284.0
        with:
          ruby-version: 3.4
      - run: |
          set -x
          which gcc
          gcc -v
          gcc -dM -E - < /dev/null | grep __MINGW || true
        shell: bash
